/**
 * @file Manages the UI interactions for the Library
 * @author Calsjunior
 */

/**
 * Global library storage
 * @type {Book[]}
 */
const myLibrary = [];
const spineColors = ["#1a2a4a", "#2a1a4a", "#1a3a2a", "#4a2a1a", "#1a3a3a", "#3a1a2a", "#2a3a1a", "#4a1a1a", "#1a1a3a"];

/**
 * The unique ID of the book that is currently being edited. Null if adding a new book.
 * @type {string}
 */
let currentEditingId = null;

/**
 * Cache DOM elements.
 * @namespace
 * @property {HTMLDivElement}    bookshelf  - The main container for book cards.
 * @property {HTMLDialogElement} dialog     - The dialog modal for adding/editing books.
 * @property {HTMLFormElement}   form       - The form inside dialog.
 * @property {HTMLButtonElement} newBookBtn - The button to open the dialog.
 */
const UI = {
    bookshelf: document.querySelector(".bookshelf"),
    dialog: document.querySelector("#add-book-dialog"),
    form: document.querySelector("#add-book-form"),
    newBookBtn: document.querySelector("#open-dialog"),
};

/**
 * Creates a new book.
 * @constructor
 * @param  {string}  title  - The title of the book.
 * @param  {string}  author - The author of the book.
 * @param  {number}  pages  - The total number of pages.
 * @param  {boolean} read   - The status of whether the book has been read or not.
 * @throws {Error}   Throws an error if not called with the new operator.
 */
function Book(title, author, pages, read) {
    if (!new.target) {
        throw Error("You must use the new operator to call the constructor");
    }

    this.id = crypto.randomUUID();
    this.title = title;
    this.author = author;
    this.pages = pages;
    this.read = read;
    this.color = spineColors[Math.floor(Math.random() * spineColors.length)];
}

Book.prototype.update = function (book) {
    this.title = book.title;
    this.author = book.author;
    this.pages = book.pages;
    this.read = book.read;
};

/**
 * Retrieves the current values from the book form that is clicked on.
 * @returns {{title: string, author: string, pages: number, read: boolean}} An object containing the formatted data.
 */
function getBookFieldsFromInput() {
    const bookTitle = UI.form.elements["book-title"].value;
    const bookAuthor = UI.form.elements["book-author"].value;
    const bookPages = UI.form.elements["book-pages"].value;
    const bookStatus = UI.form.elements["book-status"].checked;
    return {
        title: bookTitle,
        author: bookAuthor,
        pages: parseInt(bookPages, 10),
        read: bookStatus,
    };
}

/**
 * Populates the input fields of the book form.
 * @param   {string}  title  - The title of the book.
 * @param   {string}  author - The author of the book.
 * @param   {number}  pages  - The total number of pages.
 * @param   {boolean} read   - The status of whether the book has been read or not.
 * @returns {void}
 */
function setBookFieldsToInput(title, author, pages, status) {
    UI.form.elements["book-title"].value = title;
    UI.form.elements["book-author"].value = author;
    UI.form.elements["book-pages"].value = pages;
    UI.form.elements["book-status"].checked = status;
}

function addBookToLibrary(book) {
    myLibrary.push(book);
}

function removeBookFromLibrary(book) {
    const index = myLibrary.indexOf(book);
    if (index > -1) {
        myLibrary.splice(index, 1);
    }
}

/**
 * Prepares the program for editing a specific book.
 * @param   {Book} book - The book object to edit.
 * @returns {void}
 */
function editBookFromLibrary(book) {
    currentEditingId = book.id;
    setBookFieldsToInput(book.title, book.author, book.pages, book.read);
}

/**
 * Clear the bookshelf UI and re-render all books in myLibrary array.
 * @returns {void}
 */
function displayBooks() {
    UI.bookshelf.innerHTML = "";
    myLibrary.forEach((book) => {
        const card = document.createElement("article");
        card.classList.add("book");
        card.dataset.id = book.id;
        card.style.setProperty("--book-color", book.color);
        card.innerHTML = `
            <div class="spine">
                <h2 class="spine__title">${book.title}</h2>
                <hr class="spine__line">
                <p class="spine__author">${book.author}</p>
            </div>
            <!-- <button class="book__button book__button--remove">Remove Book</button> -->
            `;

        UI.bookshelf.appendChild(card);
    });
}

/**
 * Calculates rows of books and insert shelf.
 * @returns {void}
 */
function displayShelves() {
    // Remove all shelves when function start to prevent duplicate shelves
    // generated by window event listener
    const existingShelves = document.querySelectorAll(".shelf");
    for (const shelf of existingShelves) {
        shelf.remove();
    }

    const books = document.querySelectorAll(".book");
    if (books.length === 0) return;

    const rows = [];
    let previousOffset = books[0].offsetTop; // Get the current offsetTop to check if a book has wrapped
    books.forEach((book) => {
        if (book.offsetTop !== previousOffset) {
            previousOffset = book.offsetTop;
            rows.push(book);
        }
    });

    // Insert shelves only after a new book has wrapped
    rows.forEach((book) => {
        const shelf = document.createElement("div");
        shelf.classList.add("shelf");
        UI.bookshelf.insertBefore(shelf, book);
    });

    // Append a last row since it doesn't get created dynamically
    const lastShelf = document.createElement("div");
    lastShelf.classList.add("shelf");
    UI.bookshelf.appendChild(lastShelf);
}

/**
 * Reset form on new book button so no fields are filled from previous attempts.
 */
UI.newBookBtn.addEventListener("click", () => {
    UI.form.reset();
});

// Add book to myLibrary when form submit
UI.form.addEventListener("submit", (event) => {
    event.preventDefault();

    // If editing a book, update the properties
    if (currentEditingId) {
        const currentBook = myLibrary.find((book) => {
            return book.id === currentEditingId;
        });
        const updatedBook = getBookFieldsFromInput();
        currentBook.update(updatedBook);
        currentEditingId = null;
    } else {
        const newBook = getBookFieldsFromInput();
        addBookToLibrary(new Book(newBook.title, newBook.author, newBook.pages, newBook.read));
    }

    displayBooks();
    displayShelves();
    UI.dialog.close();
});

/**
 * When clicking on a book, it opens dialog for editing.
 * I have yet to implement a way to remove books after insertion.
 */
UI.bookshelf.addEventListener("click", (event) => {
    const bookCard = event.target.closest(".book");
    if (!bookCard) return;

    const targetBook = myLibrary.find((book) => book.id === bookCard.dataset.id);
    if (event.target.classList.contains("book__button--remove")) {
        removeBookFromLibrary(targetBook);
    } else {
        editBookFromLibrary(targetBook);
        UI.dialog.showModal();
    }
});

addBookToLibrary(new Book("Harry Potter One", "J.K.", 223, true));
addBookToLibrary(new Book("The Hobbit", "J.R.R", 310, false));
displayBooks();
displayShelves();

/**
 * Update the displayShelves on window resize so shelves get updated to the
 * correct row.
 */
window.addEventListener("resize", () => {
    displayShelves();
});
